### ISSUE TITLE
A bunch of Eclipse files are there and screwing stuff up

### ISSUE THREAD

**Issue by bobbysq** [frc4646/frc4646-2016-competition-code#1]
Commit 6c08c8b1ea36bd0c44eafc5c56363107c6e1bbfb appears to have taken out most of our gitignore, and now Eclipse files are there, cluttering the repo a bit. Why did we set it to keep everything but the debug folder?

**Comment by tmoser2525** [comment]
We need to re-add most of the stuff that got taken out of the gitignore. None of the compiled code should end up there and neither should most of the extra packages. It might be a good idea to create a development branch each night on the local machine and then do a pull request to the upstream repository at the end of the night. That way you get a good look at the changes before they make it into the upstream master.

**Comment by tmoser2525** [comment]
On that note it might not hurt to do multiple PRs to the upstream repo for a night so that we don't have so many large commits that touch large parts of the codebase.
